# Generated by Django 3.2.6 on 2021-08-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('units_sold', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
