# Generated by Django 3.2.6 on 2021-08-04 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
